# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20170423_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(upload_to=b''),
        ),
    ]
